from .representation import (
    Equation,
    PIRMatrixEquation,
    PIRMatrixVariable,
    PIROperators,
    PIRPartialDerivative,
    PIRHamiltonian,
    PIRLagrangian,
    PIRDerivative,
    PIRDifferentialEquation,
    PIRStateVariable,
    PIRSystem,
    PIRVectorVariable,
)
from .dimensional_analysis import dimensions_of_expression
from .units import UNIT_DIMENSIONS, dimension_signature
from .transformations import (
    canonicalize_equation,
    canonicalize_expression,
    normalize_equation,
    transform_equation,
)
from .validation import (
    PIRValidationPassResult,
    all_passed,
    detect_energy_conservation_candidate,
    detect_exchange_symmetry,
    detect_time_invariance,
    run_validation_passes,
    validate_dimensional_consistency,
)
from .serialization import (
    dump_equation_json,
    equation_from_ir_dict,
    equation_to_ir_dict,
    load_equation_json,
    read_pir_json,
    write_pir_json,
)

__all__ = [
    "Equation",
    "PIRStateVariable",
    "PIRVectorVariable",
    "PIRMatrixVariable",
    "PIRHamiltonian",
    "PIRLagrangian",
    "PIRPartialDerivative",
    "PIRDerivative",
    "PIRDifferentialEquation",
    "PIRMatrixEquation",
    "PIROperators",
    "PIRSystem",
    "dimensions_of_expression",
    "UNIT_DIMENSIONS",
    "dimension_signature",
    "canonicalize_expression",
    "canonicalize_equation",
    "normalize_equation",
    "transform_equation",
    "PIRValidationPassResult",
    "validate_dimensional_consistency",
    "detect_exchange_symmetry",
    "detect_time_invariance",
    "detect_energy_conservation_candidate",
    "run_validation_passes",
    "all_passed",
    "equation_to_ir_dict",
    "equation_from_ir_dict",
    "dump_equation_json",
    "load_equation_json",
    "write_pir_json",
    "read_pir_json",
]
